pool:
  vmImage: 'macOS 10.13'

steps:
- task: Xcode@5
  displayName: 'Run unit tests on pr'
  inputs:
    actions: 'test'
    sdk: 'iphoneos'
    scheme: 'HelloiOS'
    configuration: 'Debug'
    xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
    destinationSimulators: 'iPhone 7'
    destinationTypeOption: 'simulators'
    destinationPlatformOption: 'iOS'
    signingOption: "auto"
    useXcpretty: true
    publishJUnitResults: 'build/reports/junit.xml'

- task: Xcode@5
  displayName: 'Xcode debug build'
  inputs:
    actions: 'build'
    scheme: 'HelloiOS'
    sdk: 'iphoneos'
    configuration: 'Debug'
    xcodeVersion: 'default'
    packageApp: false
    xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
    useXcpretty: true
